### ISSUE TITLE
Upload "dir/index.html" as "dir", with text/html mime type to avoid trailing slash

### ISSUE THREAD

**Issue by michalc** [laurilehmijoki/s3_website#11]
Hi,

Would it be feasible to add a configuration parameter so html files with location in the format

dir/index.html

Are uploaded just as

dir

with text/html as the mime type? My reason is to avoid the 301 redirect generated by S3 from "dir" to "dir/" when visiting such a URL in the browser.

Would any of the authors have any guidance on what to do to add this enhancement? (Or even explanations why this isn't possible or a good idea) I'm not familiar with Ruby, but happy to learn.

Thanks,

Michal.

**Comment by thomasballinger** [comment]
Jekyll now has support for `/title` permalinks instead of `/title.html` or `title/index.html`. (see https://github.com/jekyll/jekyll/issues/3554) The main idea is the same, but perhaps special casing leaving off file extensions is a smaller scope? (or has anything else in the codebase changed to make this easier?) Now the transformation is two-part: `index.html` -> `index` and setting the content type.

**Comment by colin-air** [comment]
For what it's worth the following works for me for `Jekyll`

`Rakefile`:

```ruby
task :deploy do
  # Fresh build
  sh "bundle exec jekyll build"
  # Remove extension from all HTML files (s3_website still detects content-type text/html)
  Dir.glob('_site/**/*.html').each do |f|
      FileUtils.mv f, "#{File.dirname(f)}/#{File.basename(f,'.*')}"
  end

  # Deploy files to S3
  sh "bundle exec s3_website push"
end
```

`s3_website` does the rest!
